version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Redis用于缓存和会话管理
  # redis:
  #   image: redis:7-alpine
  #   container_name: whatsapp-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - whatsapp-network

  # 可选：添加Nginx作为反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: whatsapp-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - whatsapp-api
  #   networks:
  #     - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

# volumes:
#   redis_data: